# -*- coding: utf-8 -*-
"""GlobalEco.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fUyssx34G6xfL3QnAKE-yojNCD475KQ1
"""

import pandas as pd
from scipy import stats

filename = list(uploaded.keys())[0]

try:
    df = pd.read_csv(filename)
    print(f"\nSuccessfully loaded '{filename}':")
    print(df.head())
    print("\nDataFrame Info:")
    df.info()

    economy_type_1 = 'Developed'
    economy_type_2 = 'Developing'

    if economy_type_1 not in df['Economy_Type'].unique() or economy_type_2 not in df['Economy_Type'].unique():
        print(f"\nWarning: '{economy_type_1}' or '{economy_type_2}' not found in 'Economy_Type' column. Please adjust the economy types or the column name based on your dataset.")
    else:
        group1_gdp = df[df['Economy_Type'] == economy_type_1]['GDP'].dropna()
        group2_gdp = df[df['Economy_Type'] == economy_type_2]['GDP'].dropna()

        if len(group1_gdp) > 1 and len(group2_gdp) > 1:
            print(f"\n--- Two-sample independent t-test for GDP between '{economy_type_1}' and '{economy_type_2}' ---")

            t_stat, p_value = stats.ttest_ind(group1_gdp, group2_gdp, equal_var=False)

            print(f"Mean GDP for {economy_type_1}: {group1_gdp.mean():.2f}")
            print(f"Mean GDP for {economy_type_2}: {group2_gdp.mean():.2f}")
            print(f"T-statistic: {t_stat:.3f}")
            print(f"P-value: {p_value:.3f}")

            alpha = 0.05
            if p_value < alpha:
                print(f"Conclusion: Reject the null hypothesis. There is a significant difference in GDP between {economy_type_1} and {economy_type_2} economies (p < {alpha}).")
            else:
                print(f"Conclusion: Fail to reject the null hypothesis. There is no significant difference in GDP between {economy_type_1} and {economy_type_2} economies (p >= {alpha}).")
        else:
            print(f"\nNot enough data for t-test for '{economy_type_1}' or '{economy_type_2}'. Each group needs at least 2 samples.")

except FileNotFoundError:
    print(f"Error: File '{filename}' not found. Please ensure the file was uploaded correctly.")
except Exception as e:
    print(f"An error occurred: {e}")